apiVersion: v1
kind: Service
metadata:
  name: fcg-payments-service
  namespace: fcg-system
  labels:
    app: fcg-payments
    component: microservice
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30060
    name: http
  - port: 8081
    targetPort: 8081
    nodePort: 30062
    name: metrics
  selector:
    app: fcg-payments
