apiVersion: v1
kind: Service
metadata:
  name: fcg-notifications-service
  namespace: fcg-system
  labels:
    app: fcg-notifications
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: fcg-notifications
