apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: fcg-system
type: Opaque
data:
  sa-password: WW91clBhc3N3b3JkMTIzKio=
  connection-string-users: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlO0RhdGFiYXNlPWZjZ191c2VycztVc2VyIElkPXNhO1Bhc3N3b3JkPVlvdXJQYXNzd29yZDEyMyoqO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTs=
  connection-string-payments: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlO0RhdGFiYXNlPWZjZ19wYXltZW50cztVc2VyIElkPXNhO1Bhc3N3b3JkPVlvdXJQYXNzd29yZDEyMyoqO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTs=
  connection-string-catalog: U2VydmVyPXNxbHNlcnZlci1zZXJ2aWNlO0RhdGFiYXNlPWZjZ19jYXRhbG9nO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9WW91clBhc3N3b3JkMTIzKio7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlOw==
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-communication-secret
  namespace: fcg-system
type: Opaque
data:
  connection-string: ZW5kcG9pbnQ9aHR0cHM6Ly9mY2ctZmFzZTAyLnVuaXRlZHN0YXRlcy5jb21tdW5pY2F0aW9uLmF6dXJlLmNvbS87YWNjZXNza2V5PURTTFU5eU9QS25mUFlVUHF4cXlNZGdvWkVQcHNjYzZsQnhVRmdDVjlVbEpDbjcxZnVNZ0ZKUVFKOTlDQUFDVUx5Q3BRMmVhYkFBQUFBWkNTblh5aA==
  sender-address: RG9Ob3RSZXBseUA2ZWNkMjEyZC1jNDNjLTQ1M2ItYTAwNS00YmE5MzFmNTgxNTEuYXp1cmVjb21tLm5ldA==
