apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: fcg-system
  labels:
    app: sqlserver
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
    name: sqlserver
  selector:
    app: sqlserver
