apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: fcg-system
  labels:
    app: kafka
    component: messaging
spec:
  type: ClusterIP
  clusterIP: None 
  ports:
  - port: 29092
    targetPort: 29092
    name: internal
  - port: 9092
    targetPort: 9092
    name: external
  selector:
    app: kafka
