apiVersion: v1
kind: Service
metadata:
  name: fcg-users-service
  namespace: fcg-system
  labels:
    app: fcg-users
    component: microservice
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30050
    name: http
  - port: 8081
    targetPort: 8081
    nodePort: 30052
    name: metrics
  selector:
    app: fcg-users
