apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-catalog
  namespace: fcg-system
  labels:
    app: fcg-catalog
    component: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-catalog
  template:
    metadata:
      labels:
        app: fcg-catalog
        component: microservice
    spec:
      containers:
      - name: fcg-catalog
        image: fiapcr.azurecr.io/fcg-catalog:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: aspnetcore-environment
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: aspnetcore-urls
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: connection-string-catalog
        - name: KafkaSettings__BootstrapServers
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: bootstrap-servers
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
