apiVersion: v1
kind: Service
metadata:
  name: fcg-catalog-service
  namespace: fcg-system
  labels:
    app: fcg-catalog
    component: microservice
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30070
    name: http
  - port: 8081
    targetPort: 8081
    nodePort: 30072
    name: metrics
  selector:
    app: fcg-catalog
